server:
  port: 7200

spring:
  application:
    name: baggage-consumer-reactive

management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - mybaggage
        - mybaggage2
        - myremotefield
      correlation:
        fields:
          - mybaggage

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{mybaggage:-},%X{mybaggage2:-}]"
